### ISSUE TITLE
Custom Tasks

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#1]
Rather than:
require('./gulp/custom-task-1.js')(gulp);
require('./gulp/custom-task-2.js')(gulp);

Prefer:
// load custom tasks
require('gulp-task-loader')();

However running tasks included in this manner results in:
/usr/local/bin/node /software/scratch/hello-turris/node_modules/gulp/bin/gulp.js --color --gulpfile /software/scratch/hello-turris/gulpfile.js custom-task
[11:54:25] Using gulpfile /software/scratch/hello-turris/gulpfile.js
[11:54:25] Starting 'custom-task'...
[11:54:25] 'custom-task' errored after 179 μs
[11:54:25] TypeError: gulp.task is not a function
    at Gulp.module.exports (/software/scratch/hello-turris/gulp-tasks/custom-task.js:2:10)
    at module.exports (/software/scratch/hello-turris/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/software/scratch/hello-turris/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/software/scratch/hello-turris/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/software/scratch/hello-turris/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /software/scratch/hello-turris/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
    at Function.Module.runMain (module.js:474:11)
    at startup (node.js:117:18)

**Comment by cmelion** [comment]
Never mind, simple enough alternative:

var fs = require('fs');
var files = fs.readdirSync('./gulp');

// load custom tasks
files.forEach(function(file) {
    require('./gulp/' + file)(gulp)
});
