### ISSUE TITLE
Docker deployment for production build

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#5]
I'm able to generate, build and run the dev build via the provided instructions, but not the production build.

Docker logs show missing dependencies:

0mnpm info it worked if it ends with ok
npm info using npm@2.11.0
npm info using node@v2.2.1
npm info prestart libbyClient@1.0.0
npm info start libbyClient@1.0.0

> libbyClient@1.0.0 start /opt/application
> gulp

module.js:334
    throw err;
    ^
Error: Cannot find module 'turris-gulp-tasks'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/application/gulpfile.js:11:12)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)

**Comment by yamalight** [comment]
hm, that's a bit strange. will check it

**Comment by yamalight** [comment]
@cmelion okay, i'm slightly confused here - what do you mean by "production build"?

**Comment by cmelion** [comment]
It looks like it was something in my environment.  My colleague was able to run gulp deploy and yo docker and then run the "production" version in a docker container.

**Comment by yamalight** [comment]
I'd actually recommend pre-building the code and then packaging just the `dist/` folder into docker with nginx/apache and serving it statically. 
Will take a look into adding that as a subgenerator/additional npm scripts.
